### PR TITLE
Multiple Vector Support

### LINKED ISSUE #13: Support for multiple vectors in VectorStruct
Hey @hkulekci,

First up, I've gotta say your library is seriously useful – it's saved me loads of time. So thanks for that!

I've been using it for my [Laravel Scout engine](https://github.com/gregpriday/laravel-scout-qdrant) and noticed something. Correct me if I'm wrong, but it doesn't look like it has support for multiple vectors, even though [Qdrant's supports that](https://qdrant.tech/documentation/concepts/points/#upload-points)?

We could tweak the `VectorStruct` constructor to take an array or a string for `$name`. If it gets an array, it knows it's dealing with multiple vectors. If it's a string, then it's just a single vector. This maintains backward compat.

Here's a bit of code to show what I mean:

```php
class VectorStruct
{
    protected array $vectors;

    public function __construct(array $vector, $name = null)
    {
        // Check if $name is an array. If true, it means we have multiple vectors.
        // Otherwise, it's a single vector.
        if (is_array($name)) {
            // Multiple vectors. $vector is now an array of vector names, and $name is an array of vectors.
            $this->vectors = array_combine($vector, $name);
        } else {
            // Single vector.
            $this->vectors = [$name => $vector];
        }
    }

    public function toSearch(): array
    {
        $search = [];
        foreach ($this->vectors as $name => $vector) {
            $search[] = [
                'name' => $name,
                'vector' => $vector,
            ];
        }
        return $search;
    }

    public function toArray(): array
    {
        return $this->vectors;
    }
}
```

If you think it's a good fit, I'd be happy to throw together a PR. Or if I've got it all wrong and missed how to do this the official way, a nudge in the right direction would be awesome.

Thanks for considering!

Greg

### PR DESCRIPTION
**Pull request by gregpriday**
Resolves #13

This is still a work in progress. Not happy with it yet, and I still need to write the tests, but putting this up in case you have any comments or would prefer a different direction.

One breaking change I made was using `VectorStructInterface` for the `$vector` argument of the `Point` constructor. This makes a lot more sense to me.

I've also structured the `MultiVectorStruct` in a way that makes it only compatible with Qdrant 1.2.

### CODE REVIEW

File: src/Models/Request/Point.php [hunk 1]
```diff
@@ -8,17 +8,21 @@
...
-    protected array $vector;
+    protected VectorStructInterface $vector;
 
     /**
      * @var array|null Payload values (optional)
      */
     protected ?array $payload = null;
 
-    public function __construct(string $id, array $vector, array $payload = null)
+    public function __construct(string $id, VectorStructInterface $vector, array $payload = null)
```
Comment (gregpriday) [inline src/Models/Request/Point.php:25]: This is a breaking change, but makes more sense to me.

Comment (gregpriday) [reply src/Models/Request/Point.php:25]: For backward compatibility, we could still accept an array, and use that to construct a nameless `VectorStruct` I suppose.

**Comment by hkulekci** [comment]
I think we need to remove lock file. Our releases are more stable and no need to keep it, too. I will do it in couple of minutes.

File: src/Models/Request/Point.php (hunk 1 above)
Comment (hkulekci) [reply src/Models/Request/Point.php]: In fact, from my perspective, we don't have so many users yet. So, for this reason, we can just change some stuff freely.

**Comment by hkulekci** [comment]
We can rebase the branch to the main. I removed the `composer.lock` file.

File: src/Models/VectorStructInterface.php [hunk 2]
```diff
@@ -0,0 +1,28 @@
+<?php
+
+namespace Qdrant\Models;
+
+interface VectorStructInterface
```
Comment (hkulekci) [inline src/Models/VectorStructInterface.php:5]: I like `VectorStructInterface` to implement both `VectorStruct` and  `MultiVectorStruct`.

File: src/Models/VectorStructInterface.php [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+{
+    /**
+     * Get the name of the vector
+     *
+     * @return string
+     */
+    public function getName(): string;
```
Comment (hkulekci) [inline src/Models/VectorStructInterface.php:12]: While implementing `getName` for `MultiVectorStruct`, we need to return an array for a name or just only the first element of the array. And the result of this function won't be consistent. What do you think about removing this function from interface?

File: src/Models/Request/Point.php [hunk 4]
```diff
@@ -8,18 +8,26 @@
...
-    protected array $vector;
+    protected VectorStructInterface $vector;
 
     /**
      * @var array|null Payload values (optional)
      */
     protected ?array $payload = null;
 
-    public function __construct(string $id, array $vector, array $payload = null)
+    public function __construct(string $id, VectorStructInterface|array $vector, array $payload = null)
```
Comment (hkulekci) [inline src/Models/Request/Point.php:25]: In my opinion, we can continue with an interface instead of an array, too.

File: src/Models/PointsStruct.php [hunk 5]
```diff
@@ -42,4 +42,9 @@ public function toArray(): array
 
         return $points;
     }
+
+    public function count(): int
+    {
+        return count($this->points);
+    }
```
Comment (hkulekci) [inline src/Models/PointsStruct.php:49]: I could not remember what was the purpose of counting here.

**Comment by hkulekci** [comment]
We need to add some tests. Also, here is the documentation for multiple vector [support](https://qdrant.tech/documentation/concepts/collections/#collection-with-multiple-vectors)

File: src/Models/PointsStruct.php (hunk 5 above)
Comment (gregpriday) [reply src/Models/PointsStruct.php:49]: There were a few cases in my own code where I needed to check if the PointsStruct was empty. Strictly, I should have done all these smaller tweaks in a separate PR. I've been making a few other tweaks that I'll submit as a separate PR. This includes making this and a few other structs `Countable`.

Comment (hkulekci) [reply src/Models/PointsStruct.php:49]: It is okay for me. Doesn't seem to do any harm for now. :)

File: src/Models/Request/Point.php (hunk 4 above)
Comment (hkulekci) [reply src/Models/Request/Point.php:25]: I mean that we can continue with interface directly. Without array.

**Comment by Nikcrysis** [comment]
Hey guys, need a multiply vector support. Is it working with this realisation?

**Comment by hkulekci** [comment]
I am in vacation. I will check again as soon as possible. @Nikcrysis

**Comment by hkulekci** [comment]
Hello @gregpriday if you dont have time to finish maybe I can work on this PR. What do you think?

**Comment by hkulekci** [comment]
Okay PR rebased and I just push a change for PointsBatch request class

**Comment by gregpriday** [comment]
@hkulekci Great, I'll start working on this again today. I have a few other PRs and suggestions coming too.

**Comment by hkulekci** [comment]
Great! I just rebased the branch FYI.

File: src/Models/VectorStructInterface.php (hunk 3 above)
Comment (gregpriday) [reply src/Models/VectorStructInterface.php:12]: We need the interface to support returning just a string in some places. Here, for example: https://github.com/hkulekci/qdrant-php/pull/14/files#diff-23d49b8f87680472348ef6a2b3a63f5becaef507b78a400e4b4a9e8455762ae8R88

As far as I recall, Qdrant only supports searching a single vector field at a time. So in this case, we'll always either use the first vector, or the one the user has passed using `name`.

We could add a separate function, `getNames`, to `MultiVectorStruct`, but I'm not sure where it'd be used.

File: src/Models/Request/Point.php (hunk 4 above)
Comment (gregpriday) [reply src/Models/Request/Point.php:25]: It's been a few weeks, so just confirming that you'd like me to remove `array` as an option for `$vector` in this constructor?

It would be neater removing `array`, but for backwards compatibility it does help. We could also mark array for removal in a future version and just trigger a warning when an array is passed for `$vector`.

**Comment by gregpriday** [comment]
@hkulekci I've added some tests and made a few more changes. I can try to add a few more tests to hit the Codecov requirements.

Is there anything else on my task list for this feature or are we ready to go once I had a few more tests?

**Comment by hkulekci** [comment]
In fact, I am grateful for all this contributions. Thanks. I will do a last check after you finish all changes.

File: src/Models/VectorStructInterface.php (hunk 3 above)
Comment (hkulekci) [reply src/Models/VectorStructInterface.php:12]: Lets keep as is.
